### ISSUE TITLE
Ripple Wallet Make Payment - BigInt is not defined

### ISSUE THREAD

**Issue by robertgm** [filidorwiese/ripple-wallet#24]
On Ubuntu I tried to make payment using this command:
`ripple-wallet-cli pay --amount 1 --to rKetLK4uzotxFd27e1MaEgEUJkrYFuK5sy`

Ripple Wallet Make Payment
-----------------------------------------------

? Enter XRP amount to send: 1
? Enter destination address: rKetLK4uzotxFd27e1MaEgEUJkrYFuK5sy
? Enter destination tag (optional):
? Enter sender secret: xxxxxxxxxxmysecret

Current destination balance: 45.556226 XRP
Current sender balance: 25 XRP
? Ready to send? Yes

Preparing payment transaction...
(node:16866) UnhandledPromiseRejectionWarning: ReferenceError: BigInt is not defined
    at Function.Amount.from (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/types/amount.js:69:26)
    at /usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/types/st-object.js:128:56
    at Array.forEach (<anonymous>)
    at Function.STObject.from (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/types/st-object.js:127:16)
    at serializeObject (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/binary.js:58:32)
    at signingData (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/binary.js:74:12)
    at Object.encodeForSigning (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-binary-codec/dist/index.js:37:12)
    at computeSignature (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-lib/dist/npm/transaction/sign.js:24:41)
    at signWithKeypair (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-lib/dist/npm/transaction/sign.js:47:42)
    at RippleAPI.sign (/usr/local/lib/node_modules/ripple-wallet-cli/node_modules/ripple-lib/dist/npm/transaction/sign.js:137:16)
(node:16866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by filidorwiese** [comment]
Which version of node do you have installed? Please update to current `v12.13.0` LTS and try again
