### ISSUE TITLE
Cannot Pay

### ISSUE THREAD

**Issue by taureau75** [filidorwiese/ripple-wallet#30]
I'm having an issue running `ripple-wallet-cli pay`. Do you know what could be the reason?

```
Current destination balance: 47614.717223 XRP
Current sender balance: 437017.3102 XRP
? Ready to send? Yes

Preparing payment transaction...
/home/tk/.nvm/versions/node/v18.12.0/lib/node_modules/ripple-wallet-cli/node_modules/ripple-lib/dist/npm/transaction/sign.js:163
        return signWithKeypair(this, txJSON, ripple_keypairs_1.default.deriveKeypair(secret), options);
                                                                       ^

TypeError: Cannot read properties of undefined (reading 'deriveKeypair')
    at RippleAPI.sign (/home/tk/.nvm/versions/node/v18.12.0/lib/node_modules/ripple-wallet-cli/node_modules/ripple-lib/dist/npm/transaction/sign.js:163:72)
    at /home/tk/.nvm/versions/node/v18.12.0/lib/node_modules/ripple-wallet-cli/scripts/pay.js:165:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by filidorwiese** [comment]
Sorry, this package is no longer maintained. I'll change the status of this repo to reflect that
